#!/usr/bin/env ruby

require 'fileutils'
include FileUtils

def test_setup
  test_sublime
  test_path_setup
  test_homebrew_setup
end

def test_sublime
  `which subl`
  subl_version = `subl -v`
  return true if $? == 0 && subl_version =~ /\ASublime Text/

  STDERR.puts 'subl command is either missing or set up incorrectly.'
  false
end

def test_path_setup
  path = ENV['PATH'].split(':')
  ulb = path.index('/usr/local/bin')
  ub = path.index('/usr/bin')
  b = path.index('/bin')

  return true if ulb < ub && ulb < b

  STDERR.puts '/usr/local/bin should come before both /usr/bin and /bin in $PATH'
  false
end

def test_homebrew_command
  `which brew`
  return true if $? == 0

  STDERR.puts 'brew command is not reachable, install homebrew.'
  false
end

def test_homebrew_updated
  cd `brew --repository`
  `git fetch &> /dev/null`
  return true if `git log --oneline HEAD..origin/master | wc -l`.to_i == 0

  STDERR.puts 'brew is outdated, run `brew update`'
  false
end

def test_homebrew_setup
  test_homebrew_command &&
  test_homebrew_updated
end

test_setup